#!/usr/bin/env node
/**
 * build-html.ts — Build script (runs in Node.js at build time)
 * Reads the MCP Apps SDK browser bundle + pako from node_modules,
 * processes them, then writes generated-html.ts so the Cloudflare Worker
 * can inline them without using `fs` at runtime.
 *
 * Run: node --loader ts-node/esm src/build-html.ts
 */

import { readFileSync, writeFileSync, existsSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';
import { buildHtml, processAppBundle } from './shared.js';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, '..');

// ─── Bundle Paths ─────────────────────────────────────────────────────────────

function findBundle(candidates: string[]): { path: string; content: string } | null {
  for (const candidate of candidates) {
    const resolved = join(root, 'node_modules', candidate);
    if (existsSync(resolved)) {
      return { path: resolved, content: readFileSync(resolved, 'utf8') };
    }
  }
  return null;
}

// MCP Apps browser bundle
const appBundle = findBundle([
  '@modelcontextprotocol/ext-apps/dist/src/app.js',
  '@modelcontextprotocol/ext-apps/dist/app-with-deps.js',
  '@modelcontextprotocol/ext-apps/dist/index.js',
]);

// pako deflate for XML compression
const pakoBundle = findBundle([
  'pako/dist/pako_deflate.min.js',
  'pako/dist/pako.min.js',
  'pako/dist/pako_deflate.es5.min.js',
]);

if (!appBundle) {
  console.warn('⚠  @modelcontextprotocol/ext-apps bundle not found — using stub');
}

if (!pakoBundle) {
  console.warn('⚠  pako bundle not found — using stub');
}

// ─── Process bundles ──────────────────────────────────────────────────────────

const processedApp = appBundle
  ? processAppBundle(appBundle.content)
  : '// MCP Apps SDK not available — inline viewer disabled';

const processedPako = pakoBundle
  ? pakoBundle.content
  : '// pako not available — using fallback compression';

// ─── Generate a sample HTML to verify the pipeline ───────────────────────────

const SAMPLE_XML = `<mxGraphModel><root><mxCell id="0"/><mxCell id="1" parent="0"/>
<mxCell id="2" value="Hello draw.io" style="rounded=1;whiteSpace=wrap;html=1;" vertex="1" parent="1">
<mxGeometry x="100" y="100" width="160" height="60" as="geometry"/></mxCell>
</root></mxGraphModel>`;

const SAMPLE_EDIT_URL = 'https://app.diagrams.net/#create=sample';

const sampleHtml = buildHtml(processedApp, processedPako, SAMPLE_XML, 'Sample Diagram', SAMPLE_EDIT_URL);

// ─── Write generated-html.ts ──────────────────────────────────────────────────

const outPath = join(__dirname, 'generated-html.ts');

const output = `// AUTO-GENERATED by build-html.ts — DO NOT EDIT
// Run: npm run build:html
// Generated: ${new Date().toISOString()}

/** Pre-processed @modelcontextprotocol/ext-apps browser bundle */
export const APP_BUNDLE = ${JSON.stringify(processedApp)};

/** pako deflate bundle for XML compression */
export const PAKO_BUNDLE = ${JSON.stringify(processedPako)};

/**
 * buildPrebuiltHtml — assemble the viewer HTML for a given diagram.
 * Used by worker.ts to avoid runtime fs access.
 */
export function buildPrebuiltHtml(xml: string, title: string, editUrl: string): string {
  // Inline app + pako bundles from build-time constants
  const escapedXml = xml.replace(/\`/g, '\\\`').replace(/\\\\/g, '\\\\\\\\').replace(/\\$/g, '\\\\$');
  const escapedTitle = title.replace(/"/g, '&quot;');
  const escapedEditUrl = editUrl.replace(/"/g, '&quot;');

  return \`<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8"/>
<meta name="viewport" content="width=device-width,initial-scale=1"/>
<title>\${escapedTitle}</title>
<style>
  * { box-sizing: border-box; margin: 0; padding: 0; }
  body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif; background: #f5f5f5; }
  #header { display: flex; align-items: center; justify-content: space-between; padding: 8px 16px; background: #fff; border-bottom: 1px solid #e0e0e0; }
  #header h2 { font-size: 14px; font-weight: 600; color: #333; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; max-width: 60%; }
  #open-btn { font-size: 12px; color: #1565c0; text-decoration: none; padding: 4px 10px; border: 1px solid #1565c0; border-radius: 4px; white-space: nowrap; }
  #open-btn:hover { background: #e3f2fd; }
  #viewer-container { width: 100%; height: calc(100vh - 42px); }
  #loading { display: flex; align-items: center; justify-content: center; height: 100%; color: #999; font-size: 14px; }
</style>
</head>
<body>
<div id="header">
  <h2>\${escapedTitle}</h2>
  <a id="open-btn" href="\${escapedEditUrl}" target="_blank" rel="noopener">Open in draw.io ↗</a>
</div>
<div id="loading">Loading diagram…</div>
<div id="diagram-container" style="padding:8px;display:none;overflow:auto;max-height:calc(100vh - 42px);"></div>
<script>
\${APP_BUNDLE}
</script>
<script>
\${PAKO_BUNDLE}
</script>
<script>
(function() {
  var XML = \\\`\${escapedXml}\\\`;
  var EDIT_URL = "\${escapedEditUrl}";

  function compressXml(xml) {
    try {
      if (typeof pako !== 'undefined' && pako.deflateRaw) {
        var bytes = new TextEncoder().encode(xml);
        var compressed = pako.deflateRaw(bytes);
        var binary = '';
        for (var i = 0; i < compressed.length; i++) binary += String.fromCharCode(compressed[i]);
        return btoa(binary);
      }
    } catch(e) {}
    var bytes = new TextEncoder().encode(xml);
    var binary = '';
    for (var i = 0; i < bytes.length; i++) binary += String.fromCharCode(bytes[i]);
    return btoa(binary);
  }

  function renderDiagram() {
    var loading = document.getElementById('loading');
    try {
      // Step 1: Init MCP App SDK — connects to Claude.ai host so server is marked "ready"
      if (typeof App !== 'undefined' && App && typeof App === 'function') {
        try {
          var app = new App({ name: 'draw.io Viewer', version: '2.0.0' }, {});
          if (typeof PostMessageTransport !== 'undefined') {
            var transport = new PostMessageTransport(window.parent, window);
            app.connect(transport).catch(function() {});
          }
        } catch(appErr) {}
      }

      // Step 2: Render via Kroki.io SVG — no external scripts, works in sandboxed iframe
      var xmlBytes = new TextEncoder().encode(XML);
      var compressed = pako && pako.deflate ? pako.deflate(xmlBytes) : null;
      if (compressed) {
        var binary = '';
        for (var i = 0; i < compressed.length; i++) binary += String.fromCharCode(compressed[i]);
        var b64 = btoa(binary).replace(/\+/g, '-').replace(/\//g, '_').replace(/=/g, '');
        var krokiUrl = 'https://kroki.io/drawio/svg/' + b64;
        var img = document.createElement('img');
        img.style.cssText = 'max-width:100%;height:auto;display:block;margin:8px auto;';
        img.alt = 'draw.io diagram';
        img.onerror = function() { showDirectViewerLink(loading); };
        img.onload = function() {
          if (loading) loading.style.display = 'none';
          var dc = document.getElementById('diagram-container');
          if (dc) dc.style.display = 'block';
        };
        var dc = document.getElementById('diagram-container');
        if (dc) dc.appendChild(img);
        img.src = krokiUrl;
        return;
      }

      // Step 3: Fallback — show link to draw.io
      showDirectViewerLink(loading);
    } catch(e) {
      if (loading) loading.textContent = 'Error: ' + (e && e.message ? e.message : String(e));
    }
  }

  function showDirectViewerLink(loading) {
    if (loading) {
      loading.innerHTML = '<div style="text-align:center;padding:20px;">' +
        '<p style="color:#666;margin-bottom:12px;">Diagram ready</p>' +
        '<a href="' + EDIT_URL + '" target="_blank" rel="noopener" style="display:inline-block;padding:8px 16px;' +
        'background:#f08705;color:white;text-decoration:none;border-radius:4px;font-size:13px;">Open in draw.io ↗</a>' +
        '</div>';
    }
  }

  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', renderDiagram);
  } else {
    renderDiagram();
  }
})();
</script>
</body>
</html>\`;
}
`;

writeFileSync(outPath, output, 'utf8');

console.log(`✓ Generated: src/generated-html.ts`);
console.log(`  App bundle: ${appBundle ? Math.round(processedApp.length / 1024) + 'KB' : 'STUB'}`);
console.log(`  Pako bundle: ${pakoBundle ? Math.round(processedPako.length / 1024) + 'KB' : 'STUB'}`);
console.log(`  Sample HTML: ${Math.round(sampleHtml.length / 1024)}KB`);
